CREATE TABLE EMPLOYEE_H(
SSN INTEGER PRIMARY KEY,
NAME VARCHAR(20),
ADDR VARCHAR(30),
GENDER CHAR(10),
SALARY INTEGER,
S_SSN REFERENCES EMPLOYEE_H(SSN) ON DELETE CASCADE);

CREATE TABLE DEPT1(
DNO INT PRIMARY KEY,
DNAME VARCHAR(20),
MGR_SSN REFERENCES EMPLOYEE_H(SSN) ON DELETE CASCADE,
MGR_ST_DT VARCHAR(10));

ALTER TABLE EMPLOYEE_H
ADD DNO REFERENCES DEPT1(DNO) ON DELETE CASCADE;

CREATE TABLE DLOC1(
DNO REFERENCES DEPT1(DNO) ON DELETE CASCADE,
DLOC VARCHAR(20),
PRIMARY KEY(DNO,DLOC));

CREATE TABLE PROJECT_H(
PNO INT PRIMARY KEY,
PNAME VARCHAR(20),
PLOC VARCHAR(30),
DNO REFERENCES DEPT1(DNO) ON DELETE CASCADE);

CREATE TABLE WORKSON_H(
PNO INT,
SSN REFERENCES EMPLOYEE_H(SSN) ON DELETE CASCADE,
PRIMARY KEY(SSN, PNO),
HRS VARCHAR(20));

INSERT INTO EMPLOYEE_H VALUES('&SSN', '&NAME', '&ADDR', '&GENDER', '&SALARY', '&S_SSN', '');

INSERT INTO DEPT1 VALUES('&DNO', '&DNAME', '&MGR_SSN', '&MGR_ST_DT');

/* ALTERING TABLE EMPLOYEE_H TO ADD VALUES TO DNO */
UPDATE EMPLOYEE_H
SET DNO=5
WHERE NAME='ARMAN';

INSERT INTO DLOC1 VALUES('&DNO', '&DLOC');

INSERT INTO PROJECT_H VALUES('&PNO', '&PNAME', '&PLOC', '&DNO');

INSERT INTO WORKSON_H VALUES('&PNO', '&SSN', '&HRS');

/*  */
SELECT  DISTINCT P.PNO
FROM PROJECT_H P, DEPT1 D, EMPLOYEE_H E
WHERE E.DNO=D.DNO AND D.DNO=P.DNO AND
E.NAME='SCOTT' OR
D.MGR_SSN IN
(SELECT SSN FROM EMPLOYEE_H
WHERE NAME='SCOTT');


/* */
SELECT E.SSN, E.NAME, 1.1*E.SALARY AS RAISEDSAL 
FROM EMPLOYEE_H E, PROJECT_H P, WORKSON_H W
WHERE  P.PNAME='IOT' AND P.PNO=W.PNO AND E.SSN=W.SSN;

/* */
SELECT SUM(SALARY) AS SUMSAL, AVG(SALARY) AS AVGSAL, MIN(SALARY) AS MINSAL, MAX(SALARY) AS MAXSAL 
FROM EMPLOYEE_H E, DEPT1 D 
WHERE E.DNO=D.DNO AND D.DNAME='ACCOUNTS';

SELECT E.NAME FROM EMPLOYEE_H E 
WHERE NOT EXISTS
((SELECT PNO FROM PROJECT_H WHERE DNO='5')MINUS(SELECT PNO FROM WORKSON_H 
WHERE E.SSN=SSN)); 

SELECT D.DNO,D.DNAME,E.NAME ,
COUNT(*) AS NOOFEMP FROM EMPLOYEE_H E,DEPT1 D 
WHERE E.DNO=D.DNO AND E.SALARY>600000 AND D.DNO IN
 (SELECT E1.DNO FROM EMPLOYEE_H E1 GROUP BY E1.DNO HAVING COUNT(*)>5)
GROUP BY D.DNO,D.DNAME,E.NAME;
