/* Creating Publisher table */
CREATE TABLE PUBLISHER (NAME VARCHAR2 (20) PRIMARY KEY, PHONE INTEGER, ADDRESS VARCHAR2 (20));

/* Creating Book table */
CREATE TABLE BOOK (BOOK_ID INTEGER PRIMARY KEY, TITLE VARCHAR2 (20), PUB_YEAR VARCHAR2 (20),
PUBLISHER_NAME REFERENCES PUBLISHER (NAME) ON DELETE CASCADE);

/* Creating Book authors table */
CREATE TABLE BOOK_AUTHORS (AUTHOR_NAME VARCHAR2 (20),
BOOK_ID REFERENCES BOOK (BOOK_ID) ON DELETE CASCADE, PRIMARY KEY (BOOK_ID, AUTHOR_NAME));

/* Creating Library branch table */
CREATE TABLE LIBRARY_BRANCH (BRANCH_ID INTEGER PRIMARY KEY, BRANCH_NAME VARCHAR2 (50), ADDRESS VARCHAR2(50));

/* Creating Book copies table */
CREATE TABLE BOOK_COPIES (NO_OF_COPIES INTEGER,
BOOK_ID REFERENCES BOOK (BOOK_ID) ON DELETE CASCADE,
BRANCH_ID REFERENCES LIBRARY_BRANCH (BRANCH_ID) ON DELETE CASCADE, PRIMARY KEY (BOOK_ID, BRANCH_ID));

/* Creating Card table */
CREATE TABLE CARD (CARD_NO INTEGER PRIMARY KEY);

/* Creating Book lending table */
CREATE TABLE BOOK_LENDING (DATE_OUT DATE, DUE_DATE DATE,
BOOK_ID REFERENCES BOOK (BOOK_ID) ON DELETE CASCADE, BRANCH_ID REFERENCES
LIBRARY_BRANCH (BRANCH_ID) ON DELETE CASCADE, CARD_NO REFERENCES CARD (CARD_NO) ON DELETE CASCADE, PRIMARY KEY (BOOK_ID, BRANCH_ID, CARD_NO));

/* Inserting elements into Publisher table */
INSERT INTO PUBLISHER VALUES ('&NAME', &PHONE, '&ADDRESS');

/* Inserting elements into Book table */
INSERT INTO BOOK VALUES ('&BOOK_ID', '&TITLE', '&PUB_YEAR', '&PUBLISHER_NAME');

/* Inserting elements into Book authors table */
INSERT INTO BOOK_AUTHORS VALUES ('&AUTHOR_NAME', '&BOOK_ID');

/* Inserting elements into Library branch table */
INSERT INTO LIBRARY_BRANCH VALUES ('&BRANCH_ID', '&BRANCH_NAME', '&ADDRESS');

/* Inserting elements into Book copies table */
INSERT INTO BOOK_COPIES VALUES ('&NO_OF_COPIES', '&BOOK_ID', '&BRANCH_ID');

/* Inserting elements into Card table */
INSERT INTO CARD VALUES ('&CARD_NO');

/* Inserting elements into Book lending table */
INSERT INTO BOOK_LENDING VALUES ('&DATE_OUT', '&DUE_DATE', '&BOOK_ID', '&BRANCH_ID', '&CARD_NO');

/* Combining tables */
SELECT B.BOOK_ID, B.TITLE, B.PUBLISHER_NAME, A.AUTHOR_NAME, C.NO_OF_COPIES, L.BRANCH_ID
FROM BOOK B, BOOK_AUTHORS A, BOOK_COPIES C, LIBRARY_BRANCH L
WHERE B.BOOK_ID = A.BOOK_ID AND C.BOOK_ID = B.BOOK_ID AND L.BRANCH_ID = C.BRANCH_ID; 

/* To determine people who have taken more than 3 book in a given period of time */
SELECT L.CARD_NO
FROM BOOK_LENDING L
WHERE DATE_OUT BETWEEN '01-JAN-17' AND '30-JUN-17'
GROUP BY L.CARD_NO
HAVING COUNT(*)>3;

/* */
CREATE VIEW PUB_YEAR AS
SELECT PUB_YEAR
FROM BOOK;
