CREATE TABLE EMPLOYEE_H(
SSN INTEGER PRIMARY KEY,
NAME VARCHAR(20),
ADDR VARCHAR(30),
GENDER CHAR(10),
SALARY INTEGER,
S_SSN REFERENCES EMPLOYEE_H(SSN) ON DELETE CASCADE);

CREATE TABLE DEPT1(
DNO INT PRIMARY KEY,
DNAME VARCHAR(20),
MGR_SSN REFERENCES EMPLOYEE_H(SSN) ON DELETE CASCADE,
MGR_ST_DT VARCHAR(10));

ALTER TABLE EMPLOYEE_H
ADD DNO REFERENCES DEPT1(DNO) ON DELETE CASCADE;

CREATE TABLE DLOC1(
DNO REFERENCES DEPT1(DNO) ON DELETE CASCADE,
DLOC VARCHAR(20),
PRIMARY KEY(DNO,DLOC));

CREATE TABLE PROJECT_H(
PNO INT PRIMARY KEY,
PNAME VARCHAR(20),
PLOC VARCHAR(30),
DNO REFERENCES DEPT1(DNO) ON DELETE CASCADE);

CREATE TABLE WORKSON_H(
PNO INT,
SSN REFERENCES EMPLOYEE_H(SSN) ON DELETE CASCADE,
PRIMARY KEY(SSN, PNO),
HRS VARCHAR(20));

INSERT INTO EMPLOYEE_H VALUES('&SSN', '&NAME', '&ADDR', '&GENDER', '&SALARY', '&S_SSN', '');

INSERT INTO DEPT1 VALUES('&DNO', '&DNAME', '&MGR_SSN', '&MGR_ST_DT');

/* ALTERING TABLE EMPLOYEE_H TO ADD VALUES TO DNO */
UPDATE EMPLOYEE_H
SET DNO=5
WHERE NAME='ARMAN';

INSERT INTO DLOC1 VALUES('&DNO', '&DLOC');

INSERT INTO PROJECT_H VALUES('&PNO', '&PNAME', '&PLOC', '&DNO');

INSERT INTO WORKSON1 VALUES('&PNO', '&SSN', '&HRS');
