CREATE TABLE SALESMAN(
SALESMAN_ID INT PRIMARY KEY,
NAME VARCHAR(20),
COMMISSION CHAR(4));

CREATE TABLE CUSTOMER(CUSTOMER_ID INT PRIMARY KEY,
CUST_NAME VARCHAR(20),
CITY VARCHAR(20),
GRADE INT,
SALESMAN_ID REFERENCES SALESMAN(SALESMAN_ID) ON DELETE  SET NULL);

CREATE TABLE ORDERS(ORD_NO INT PRIMARY KEY,
PURCHASE_AMT NUMBER,
ORD_DATE DATE,
CUSTOMER_ID REFERENCES CUSTOMER(CUSTOMER_ID),
SALESMAN_ID REFERENCES SALESMAN(SALESMAN_ID) ON DELETE CASCADE);
