/* CREATING TABLE SALESMAN */
CREATE TABLE SALESMAN(
SALESMAN_ID INT PRIMARY KEY,
NAME VARCHAR(20),
CITY VARCHAR(20),
COMMISSION CHAR(4));

/* CREATING TABLE CUSTOMER */
CREATE TABLE CUSTOMER(CUSTOMER_ID INT PRIMARY KEY,
CUST_NAME VARCHAR(20),
CITY VARCHAR(20),
GRADE INT,
SALESMAN_ID REFERENCES SALESMAN(SALESMAN_ID) ON DELETE  SET NULL);

/* CREATING TABLE ORDERS */
CREATE TABLE ORDERS(ORD_NO INT PRIMARY KEY,
PURCHASE_AMT NUMBER,
ORD_DATE DATE,
CUSTOMER_ID REFERENCES CUSTOMER(CUSTOMER_ID),
SALESMAN_ID REFERENCES SALESMAN(SALESMAN_ID) ON DELETE CASCADE);

/* INSERTING DATA INTO SALESMAN TABLE */
INSERT INTO SALESMAN VALUES ('&SALESMAN_ID', '&NAME', '&CITY', '&COMMISSION');

/* INSERTING DATA INTO CUSTOMER TABLE */
INSERT INTO CUSTOMER VALUES ('&CUSTOMER_ID', '&CUST_NAME', '&CITY', '&GRADE', '&SALESMAN_ID');

/* INSERTING DATA INTO ORDERS TABLE */
INSERT INTO ORDERS VALUES ('&ORD_NO', '&PURCHASE_AMT', '&ORD_DATE', '&CUSTOMER_ID', '&SALESMAN_ID');

/* COUNT OF CITIES WITH GRADE > THE AVG GRADE OF BANGALORE */
SELECT COUNT(CUSTOMER_ID)
FROM CUSTOMER
WHERE GRADE >(
SELECT AVG(GRADE)
FROM CUSTOMER
WHERE CITY='BANGALORE');

/* FIND NAME AND NUMBER OF THE SALES MAN */
SELECT NAME, SALESMAN_ID
FROM SALESMAN S
WHERE(
SELECT COUNT(*)
FROM CUSTOMER 
WHERE SALESMAN_ID=S.SALESMAN_ID)>1;

/* UNION OF A LIST WITH SALESMAN WITH CUST IN HIS CITY AND LIST WITH SALESMAN WITHOUT CUST IN HIS CITY */
SELECT S.SALESMAN_ID, NAME, CUST_NAME
FROM SALESMAN S, CUSTOMER C WHERE S.CITY=C.CITY AND S.SALESMAN_ID=C.SALESMAN_ID
UNION
SELECT S.SALESMAN_ID, NAME, 'NO MATCH'
FROM SALESMAN S, CUSTOMER C WHERE NOT S.CITY=ANY(SELECT CITY FROM CUSTOMER);

/* SALESMAN WITH MAX SALES IN A DAY */
CREATE VIEW SALESMAN_ORDER AS SELECT B.ORD_DATE, A.SALESMAN_ID, NAME
FROM SALESMAN A, ORDERS B
WHERE A.SALESMAN_ID=B.SALESMAN_ID AND B.PURCHASE_AMT=
(SELECT MAX(PURCHASE_AMT) FROM ORDERS C WHERE C.ORD_DATE=B.ORD_DATE);

/* DELETE SALESMAN_ID = 1000 */
DELETE FROM SALESMAN
WHERE SALESMAN_ID=1000;
